- hosts: terraform-ansible
  tasks:
    - name: Create index.html file
      copy:
        dest: /home/ubuntu/index.html
        content: <h1>Feito com Terraform e Ansible</h1>
    
    - name: Create web server
      shell: "nohup busybox httpd -f -p 8080 &"